import type { ClusterCandidate, NodeCandidate } from './twoLevelRl'

export const mockWorkspaceClusters: ClusterCandidate[] = [
  {
    uuid: 'cluster-north-a',
    name: '华北生产集群 A',
    region: '华北',
    authorized: true,
    status: 'healthy',
    cpuFreeCores: 128,
    memoryFreeGiB: 512,
    gpuFree: 2,
    electricityPrice: 0.46,
    batterySoc: 68,
    currentPowerW: 1180,
    powerLimitW: 2400
  },
  {
    uuid: 'cluster-east-b',
    name: '华东边缘集群 B',
    region: '华东',
    authorized: true,
    status: 'healthy',
    cpuFreeCores: 96,
    memoryFreeGiB: 384,
    gpuFree: 4,
    electricityPrice: 0.62,
    batterySoc: 76,
    currentPowerW: 1320,
    powerLimitW: 2600
  },
  {
    uuid: 'cluster-south-c',
    name: '华南算力集群 C',
    region: '华南',
    authorized: true,
    status: 'warning',
    cpuFreeCores: 72,
    memoryFreeGiB: 192,
    gpuFree: 0,
    electricityPrice: 0.38,
    batterySoc: 18,
    currentPowerW: 1880,
    powerLimitW: 1950
  },
  {
    uuid: 'cluster-west-d',
    name: '西部备用集群 D',
    region: '西部',
    authorized: false,
    status: 'healthy',
    cpuFreeCores: 160,
    memoryFreeGiB: 640,
    gpuFree: 8,
    electricityPrice: 0.41,
    batterySoc: 82,
    currentPowerW: 1120,
    powerLimitW: 3000
  }
]

export const mockWorkspaceNodes: NodeCandidate[] = [
  {
    id: 'north-a-node-01',
    clusterUuid: 'cluster-north-a',
    name: 'north-a-node-01',
    status: 'Ready',
    cpuCapacityCores: 64,
    cpuFreeCores: 42,
    cpuUsage: 0.4,
    memoryFreeGiB: 160,
    gpuFree: 0,
    currentPowerW: 206,
    powerLimitW: 520,
    idlePowerW: 90,
    maxPowerW: 460
  },
  {
    id: 'north-a-node-02',
    clusterUuid: 'cluster-north-a',
    name: 'north-a-node-02',
    status: 'Ready',
    cpuCapacityCores: 64,
    cpuFreeCores: 46,
    cpuUsage: 0.34,
    memoryFreeGiB: 176,
    gpuFree: 1,
    currentPowerW: 232,
    powerLimitW: 620,
    idlePowerW: 96,
    maxPowerW: 540
  },
  {
    id: 'north-a-node-03',
    clusterUuid: 'cluster-north-a',
    name: 'north-a-node-03',
    status: 'Ready',
    cpuCapacityCores: 48,
    cpuFreeCores: 28,
    cpuUsage: 0.58,
    memoryFreeGiB: 112,
    gpuFree: 1,
    currentPowerW: 258,
    powerLimitW: 420,
    idlePowerW: 88,
    maxPowerW: 390
  },
  {
    id: 'east-b-node-01',
    clusterUuid: 'cluster-east-b',
    name: 'east-b-node-01',
    status: 'Ready',
    cpuCapacityCores: 64,
    cpuFreeCores: 50,
    cpuUsage: 0.36,
    memoryFreeGiB: 192,
    gpuFree: 4,
    currentPowerW: 318,
    powerLimitW: 760,
    idlePowerW: 132,
    maxPowerW: 710
  },
  {
    id: 'east-b-node-02',
    clusterUuid: 'cluster-east-b',
    name: 'east-b-node-02',
    status: 'Ready',
    cpuCapacityCores: 48,
    cpuFreeCores: 30,
    cpuUsage: 0.48,
    memoryFreeGiB: 128,
    gpuFree: 0,
    currentPowerW: 214,
    powerLimitW: 520,
    idlePowerW: 92,
    maxPowerW: 430
  },
  {
    id: 'east-b-node-03',
    clusterUuid: 'cluster-east-b',
    name: 'east-b-node-03',
    status: 'Unschedulable',
    cpuCapacityCores: 48,
    cpuFreeCores: 36,
    cpuUsage: 0.28,
    memoryFreeGiB: 96,
    gpuFree: 0,
    currentPowerW: 172,
    powerLimitW: 420,
    idlePowerW: 84,
    maxPowerW: 380
  },
  {
    id: 'south-c-node-01',
    clusterUuid: 'cluster-south-c',
    name: 'south-c-node-01',
    status: 'Ready',
    cpuCapacityCores: 48,
    cpuFreeCores: 20,
    cpuUsage: 0.72,
    memoryFreeGiB: 80,
    gpuFree: 0,
    currentPowerW: 320,
    powerLimitW: 340,
    idlePowerW: 86,
    maxPowerW: 360
  }
]
